export const CollectionName = {
  menu: "menu",
  user: "user",
  office: "office",
  main_location: "main_location",
  bod: "board_of_directors",
  caseStudy: "case_study",
  brochure: "brochure",
  resourceCategory: "resource_category",
  slider: "slider",
  page: "page",
  partnerAndAlliance: "partner_and_alliance",
  template: "template",
  contact: "contact",
  pressRelease: "press_release",
  jobCategory: "career_job_category",
  job: "career_job",
  application: "career_application",
  investorPolicies: "investor_policies",
  investorFinancialInfo: "investor_financial_info",
  investorAnnualReport: "investor_annual_report",
  investorCommittee: "investor_committee",
  investorNotice:"investor_notice",
  investorStockExchangeFiling:"investor_stock_exchange_filing",
  investorPdf:"investor_pdf",
  investorPdfWithTitle:"investor_pdf_with_title",
  investorShareHoldingPattern:"investor_share_holding_pattern",
  investorPostalBallot:"investor_postal_ballot",
  investorSubsidiariesFinancial:"investor_subsidiaries_financial",
  investorFeedback:"investor_feedback",
  investorBuyBack:"investor_buyback",
  investorTradingWindow:"investor_trading_window",
  unsubscribe:"unsubscribe",
} as const;

type ValueOf<T> = T[keyof T];
export type CollectionNameType = ValueOf<typeof CollectionName>;
